### ISSUE TITLE
MRI_dict parsing issue

### ISSUE THREAD

**Issue by shivambans15** [nih-megcore/nih_to_mne#49]
Traceback (most recent call last):
  File "/data/ML_MEG/vol_surf_compare.py", line 214, in <module>
    full_process(subject, fmin=fmin, fmax=fmax, vol_src=False)
  File "/data/ML_MEG/vol_surf_compare.py", line 96, in full_process
    mri_dict = get_mri_dict(subjid, task='sternberg', project='nihmeg', bids_root=bids_root)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bansals3/.local/lib/python3.11/site-packages/nih2mne/utilities/bids_helpers.py", line 109, in get_mri_dict
    project_root = get_project(bids_root, project)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bansals3/.local/lib/python3.11/site-packages/nih2mne/utilities/bids_helpers.py", line 60, in get_project
    raise ValueError(f"""Indeterminant amount of project folders: {tmp_}.
ValueError: Indeterminant amount of project folders: ['/data/ML_MEG/NIH_hvmeg/derivatives/New folder', '/data/ML_MEG/NIH_hvmeg/derivatives/OSLaddons', '/data/ML_MEG/NIH_hvmeg/derivatives/airpuff', '/data/ML_MEG/NIH_hvmeg/derivatives/airpuff2', '/data/ML_MEG/NIH_hvmeg/derivatives/airpuff3', '/data/ML_MEG/NIH_hvmeg/derivatives/ica', '/data/ML_MEG/NIH_hvmeg/derivatives/new', '/data/ML_MEG/NIH_hvmeg/derivatives/nihmeg', '/data/ML_MEG/NIH_hvmeg/derivatives/sterberg_res', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_beamforming_trial', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_newsubjs', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_13_35_final', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_13_35_post_ica_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_1_45_post_ica_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_35_55', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_35_55_post_ica_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_3_6', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_3_6_final', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_3_6_fix', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_3_6_post_ica_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_8_12_final', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_res_8_12_post_ica_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_surf', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_surf_3', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_test', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_vol', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_vol_2', '/data/ML_MEG/NIH_hvmeg/derivatives/sternberg_vol_3', '/data/ML_MEG/NIH_hvmeg/derivatives/tmp'].
                         Specify at the commandline the expected project

**Comment by jstout211** [comment]
We investigated this and it is a configuration setting with ./local/python...  that is causing a stale install to be used rather than the lua module install
